name = "miR_iFFL"
uuid = "9f552b52-0809-4f8d-8981-ca23912da97e"
authors = ["Christopher Johnstone <meson800@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
Catalyst = "479239e8-5488-4da2-87a7-35f2df7eef83"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"

[compat]
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
